Initial test logic
Azure/terraform-azurerm-caf-enterprise-scale pull request #22
Opened 2020-12-05 18:22 UTC by ljtill

[Under development]

2021-01-27 11:03 UTC, krowlandson requested changes
Looking great, thank you.

Let's run through the comments offline and get this merged.

2021-01-27 11:03 UTC, krowlandson commented on tests/deployment/lib/archetype_definitions/archetype_definition_customer_sap.json
> +{
We should probably remove this one and just specify the `default_empty` archetype definition ID where this is currently used.

2021-01-27 11:03 UTC, krowlandson commented on tests/deployment/lib/archetype_definitions/archetype_definition_customer_landing_zone.tmpl.json
> +{
We should probably remove this one and just specify the `default_empty` archetype definition ID where this is currently used.

2021-01-27 11:03 UTC, krowlandson commented on tests/deployment/lib/archetype_definitions/archetype_definition_customer_corp.json
> +{
We should probably remove this one and just specify the `default_empty` archetype definition ID where this is currently used.

2021-01-27 11:34 UTC, krowlandson commented on tests/deployment/lib/archetype_definitions/archetype_definition_customer_corp.json
> +{
Updated in commit [Cleanup archetype definitions and variables](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/22/commits/cb736560540e4718a92e62ba256290f3382aa89f)

2021-01-27 11:34 UTC, krowlandson commented on tests/deployment/lib/archetype_definitions/archetype_definition_customer_landing_zone.tmpl.json
> +{
Updated in commit [Cleanup archetype definitions and variables](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/22/commits/cb736560540e4718a92e62ba256290f3382aa89f)

2021-01-27 11:34 UTC, krowlandson commented on tests/deployment/lib/archetype_definitions/archetype_definition_customer_sap.json
> +{
Updated in commit [Cleanup archetype definitions and variables](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/22/commits/cb736560540e4718a92e62ba256290f3382aa89f)

2021-01-27 11:35 UTC, krowlandson commented on tests/scripts/tf-prepare.sh
> +sed -i 's/version = ""/version = "'$TF_AZ_VERSION'"/g' main.tf
Updated in commit [Replaced `version` with `required_providers` block](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/22/commits/71a3d80c2e5b0c6919b1d22af0201cf08e0dca22)

2021-01-27 11:44 UTC, krowlandson commented on tests/deployment/lib/policy_assignments/policy_assignment_test_policy_set_definition.json
> +    "sku": {
Found reference to this in the [ARM Template documentation for Policy Assignments](https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/policyassignments):

> The policy sku. This property is optional, obsolete, and will be ignored.

Have removed from the custom policy assignment templates in our test deployment, and will remove from all built-in policy assignment templates as part of the next policy refresh.

Update applied in commit [Remove obsolete `sku` block from templates](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/22/commits/01abb7575f6c2b6c595356a58dd6beb64d65bd96).

2021-02-05 11:33 UTC, ljtill commented on tests/scripts/tf-install.sh
> +mv /tmp/terraform /home/runner/.terraform/bin/terraform
Correct - I've reviewed the test jobs and we have isolation between each version within the matrix.

2021-02-05 13:11 UTC, ljtill commented on tests/scripts/tf-init.sh
> +cd $PWD/tests/deployment
Replaced the $PWD variable with a pipelines variables instead to better support this.

2021-02-05 13:22 UTC, ljtill commented on tests/scripts/tf-destroy.sh
> +cd $PWD/tests/deployment
Replaced the $PWD variable with a pipelines variables instead to better support this.

2021-02-08 14:47 UTC, krowlandson approved these changes

2021-02-08 14:51 UTC, merged