feat!: implement hub network mesh peering
Azure/terraform-azurerm-caf-enterprise-scale pull request #429
Opened 2022-07-28 16:10 UTC by matt-FFFFFF

## Overview/Summary

Implements option to peer hub networks with new configuration:

`var.configure_connectivity_resources.settings.hub_networks[*].config.enable_hub_network_mesh_peering`

## This PR fixes/adds/changes/removes

1. fixes #258
2. Update docs for release v2.2.0
3. Adds docs for strict MG association non-idempotency

### Breaking Changes

1. Adds new attribute to complex object variable, therefore breaking change.

## Testing Evidence

Test with two hubs. Hub mesh peering enabled and also peering to one other spoke:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/16320656/181586455-f0ac4116-b99d-4b6d-8b7e-b9c174ea9a27.png">

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

2022-07-29 12:08 UTC, matt-FFFFFF commented
/azp run unit

2022-07-29 12:14 UTC, matt-FFFFFF commented
/azp run unit

2022-07-29 12:16 UTC, matt-FFFFFF commented
/azp run unit

2022-07-29 12:22 UTC, matt-FFFFFF commented
/azp run update

2022-07-29 12:26 UTC, matt-FFFFFF commented
/azp run unit

2022-07-29 12:51 UTC, krowlandson requested changes
Looking great... just a couple of minor things which I'll discuss direct.

2022-07-29 12:51 UTC, krowlandson commented on modules/connectivity/locals.tf
> +  azurerm_virtual_network_peering = flatten([
Can you use `distinct(concat())` instead?

e.g.
```
  azurerm_virtual_network_peering = distinct(concat(
    local.azurerm_virtual_network_peering_hubs,
    local.azurerm_virtual_network_peering_spokes,
  ))
```

2022-07-29 12:51 UTC, krowlandson commented on modules/connectivity/locals.tf
> +  virtual_network_hub_peerings = {
Are we able to update this to reflect how names and resource IDs are created for the standard peering please? This allows us to offer the opportunity for user overrides through the advanced config block (something which has been explicitly asked for in a previous issue for this resource type.

Please also add new `locals` to the `debug` output

2022-07-29 13:51 UTC, matt-FFFFFF commented
/azp run update

2022-07-29 13:54 UTC, matt-FFFFFF commented
/azp run unit

2022-07-29 14:05 UTC, matt-FFFFFF commented
/azp run e2e

2022-07-29 14:18 UTC, krowlandson submitted a review, later dismissed
If the tests pass, then LGTM 😄

2022-07-29 15:17 UTC, matt-FFFFFF commented
/azp run update

2022-07-29 15:19 UTC, matt-FFFFFF commented
/azp run unit

2022-07-29 15:19 UTC, matt-FFFFFF commented
/azp run e2e

2022-07-29 20:46 UTC, matt-FFFFFF commented
/azp run e2e

2022-08-11 08:36 UTC, matt-FFFFFF commented
/azp run unit

2022-08-11 08:48 UTC, matt-FFFFFF commented
/azp run e2e

2022-08-12 08:30 UTC, matt-FFFFFF commented
e2e worked on 5/6 matrix builds, job timeout after 60m caused state errors on 1:

https://dev.azure.com/mscet/CAE-ALZ-Terraform/_build/results?buildId=8104&view=logs&j=c43ef2bb-207d-5b12-fc26-01a84a3b13ab

2022-08-12 12:58 UTC, krowlandson approved these changes
LGTM 🚀

2022-08-12 13:24 UTC, merged