Removed Activity Log solution from Terraform RI
Azure/terraform-azurerm-caf-enterprise-scale pull request #554
Opened 2022-12-13 05:54 UTC by lachaves

## Overview/Summary

As per ADO USER STORY 25142

1. Remove Activity Log solution from Terraform RI
2. Update and Terraform documentation referencing this

## This PR fixes/adds/changes/removes

1. Issue #553 

### Breaking Changes

1.  Need validation from team

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

![ALZ tf deployment](https://user-images.githubusercontent.com/32776049/207237752-ddca6653-6e76-4667-9d2e-b6686a718984.png)

![examples-deploy-management-resources](https://user-images.githubusercontent.com/32776049/207237398-03d25fd8-be51-4e64-9da7-b6f8c8179caa.png)

## As part of this Pull Request I have

- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [ x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x ] Performed testing and provided evidence.
- [ x] Updated relevant and associated documentation.
- [X ] Updated the ["RELEASE"](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues) page with details needed for when this code change is released.

2022-12-13 10:44 UTC, krowlandson commented
/azp run update

2022-12-13 10:58 UTC, krowlandson requested changes
Looks good @lachaves... just one thing missing that I can see.

Please can you update `docs/wiki/media/examples-deploy-management-custom-resources.png` as per [`docs/wiki/media/examples-deploy-management-resources.png`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/554/files#diff-64cf8a91cd99250366a6a665c2921f15bc7c022d8006b238c53c2f160cefec1a)?

I believe these are actually the same image, but referenced by different names in case we decide to customise the list of solutions in the example at some point. Perhaps this might be a good time to do this actually? 👍🏻

2022-12-13 14:43 UTC, lachaves commented
@krowlandson, sure, so the idea is to remove some of the solutions and have a different image for custom management solutions, right? Anything else for the new image?

2022-12-13 22:01 UTC, lachaves commented
@krowlandson, Ill fix the Code Review/Lint errors so it can finish the checks

2022-12-14 08:07 UTC, krowlandson requested changes
Thank you @lachaves 

I'm addressing my comments on this review pass, but please can you ensure the images for the wiki reflect the correct locations for default (`eastus`) and custom (`uksouth`)?

2022-12-14 08:07 UTC, krowlandson commented on docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
> +  - Set the local `configure_management_resources` input variable in the  `settings.management.tf` file for a custom deployment of the management resources solutions. If set to false the solution wil
Just an FYI... I am updating this to a more succinct statement

2022-12-14 08:07 UTC, krowlandson commented on docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
> +  default = "eastus"
Just an FYI, I am reverting this to `uksouth` as `eastus` is the global module default for this and the point of the custom demo is to set a different location.

2022-12-14 08:11 UTC, krowlandson commented
/azp run update

2022-12-16 09:19 UTC, krowlandson commented
/azp run unit

2022-12-16 09:19 UTC, krowlandson approved these changes
LGTM 🚀

2022-12-16 09:56 UTC, merged