Microsoft defender for Cloud policy update
Azure/terraform-azurerm-caf-enterprise-scale pull request #709
Opened 2023-05-10 15:42 UTC by steph409

## Overview/Summary

it is now possible to set all parameters from this policy in terraform. One of those parameters was asked for in #584 

## This PR fixes/adds/changes/removes

1. fix - there was a typo in the initiative definition (`Effect` instead of `effect`) which is why the `enableAscForKeyVault` did not work as expected.
2. there were some parameters, e.g. `enableAscForCosmosDbs`, which were not taken from `configure_management_resources`. I added all the ones which were missing.
3. updated some policy related documentation.

### Breaking Changes

NONE

## Testing Evidence

missing parameters are working now, I used the following configuration for testing:
```hcl
# Configure the management resources settings.
locals {
  configure_management_resources = {
    settings = {
      log_analytics = {
        enabled = true
        config = {
          retention_in_days                           = 30
          enable_monitoring_for_arc                   = false
          enable_monitoring_for_vm                    = false
          enable_monitoring_for_vmss                  = false
          enable_solution_for_agent_health_assessment = false
          enable_solution_for_anti_malware            = false
          enable_solution_for_azure_activity          = false
          enable_solution_for_change_tracking         = false
          enable_solution_for_service_map             = false
          enable_solution_for_sql_assessment          = false
          enable_solution_for_updates                 = false
          enable_solution_for_vm_insights             = false
          enable_solution_for_container_insights      = false
          enable_sentinel                             = false
        }
      }
      security_center = {
        enabled = true
        config = {
          email_security_contact                                = var.security_alerts_email_address
          enable_defender_for_apis                              = true
          enable_defender_for_app_services                      = true
          enable_defender_for_arm                               = true
          enable_defender_for_containers                        = false
          enable_defender_for_cosmosdbs                         = false
          enable_defender_for_cspm                              = true
          enable_defender_for_dns                               = false
          enable_defender_for_key_vault                         = true
          enable_defender_for_oss_databases                     = true
          enable_defender_for_servers                           = true
          enable_defender_for_servers_vulnerability_assessments = true
          enable_defender_for_sql_servers                       = true
          enable_defender_for_sql_server_vms                    = true
          enable_defender_for_storage                           = false
        }
      }
    }
  }
}

````

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [X] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated relevant and associated documentation.

2023-05-11 20:24 UTC, matt-FFFFFF commented
Thanks @steph409 another good add. Will properly review and run tests tomorrow

2023-05-12 10:17 UTC, matt-FFFFFF commented
/azp run unit

2023-05-12 11:13 UTC, matt-FFFFFF commented
/azp run unit

2023-05-12 11:23 UTC, matt-FFFFFF requested changes

2023-05-12 11:23 UTC, matt-FFFFFF commented on modules/management/locals.tf
Hi @steph409 The tests are failing, you need to update this local block to map the settings:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/967bccc691164417eac7db92432b20cec346c3f5/modules/management/locals.tf#L43-L77

2023-05-16 17:25 UTC, steph409 commented on modules/management/locals.tf
hi,
I had those changed but it seems I did not commit them, sorry for that! let me know if it is good now :)

2023-05-17 17:04 UTC, matt-FFFFFF commented on modules/management/locals.tf
Thank you! Looks great :)

2023-05-17 17:05 UTC, matt-FFFFFF commented
/azp run unit

2023-05-17 17:05 UTC, matt-FFFFFF submitted a review, later dismissed

2023-05-18 12:45 UTC, matt-FFFFFF commented
/azp run update

2023-05-18 13:37 UTC, matt-FFFFFF commented
/azp run update

2023-05-18 22:00 UTC, matt-FFFFFF commented
/azp run unit

2023-05-19 09:52 UTC, matt-FFFFFF approved these changes

2023-05-19 09:53 UTC, matt-FFFFFF commented
LGTM!

2023-05-19 09:53 UTC, merged