Bug vpn client config
Azure/terraform-azurerm-caf-enterprise-scale pull request #792
Opened 2023-08-17 14:38 UTC by gogondi1

## Overview/Summary
unable to configure vpn_client_configuration due to revoked_certificate block defined with wrong parameters #791

in hub and spoke model when try to configure vpn_client_configuration under virtual_network_gateway, error is receiving due to one of the parameter under revoked_certificate is wrong, public_cert_data under revoked_certificate block need to replace by "thumbprint" according to terraform documentation. 

[![Screenshot 2023-08-16 at 14 55 12](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/53465177/e6fc5ec4-75e8-4282-9566-853abd369707)(url)
## This PR fixes/adds/changes/removes

1.  you can configure vpn_client_config successfully 

### Breaking Changes

1. if issue with current modification replace thumbprint with public_cert_data  

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

[![Screenshot 2023-08-17 at 15 36 42](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/53465177/781b7918-dc89-4001-87a6-c09342001c53)(url)

[![Screenshot 2023-08-17 at 15 34 16](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/53465177/c904ace9-5514-4e45-9607-8461137b4428)(url)
## As part of this Pull Request I have

- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [ x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x ] Performed testing and provided evidence.
- [x ] Updated relevant and associated documentation.

2023-08-25 05:50 UTC, gogondi1 commented
@microsoft-github-policy-service agree

2023-08-25 08:28 UTC, jtracey93 requested changes

2023-08-25 08:28 UTC, jtracey93 commented on .github/policies/cla.yml
Can this file be removed please?

2023-08-25 08:28 UTC, jtracey93 commented on .github/policies/platformcontext.yml
can this file be removed please?

2023-08-25 08:32 UTC, gogondi1 commented on .github/policies/platformcontext.yml
yes

2023-09-04 08:55 UTC, gogondi1 reviewed
I have delete cla.yml and platformcontext.yml files, could anyone please review

2023-09-26 13:19 UTC, gogondi1 reviewed
I request to review the changes and merge the branches

2023-09-28 16:05 UTC, matt-FFFFFF approved these changes

2023-10-07 11:10 UTC, matt-FFFFFF commented
Thank you for this pr - since I could not push to your fork to update from main, I pulled your changes into a new branch that I can work on. Therefore closing in favour of #835

2023-10-07 11:10 UTC, closed without merging