feat(connectivity): Add option to set allow_non_virtual_wan_traffic in express route gateway.
Azure/terraform-azurerm-caf-enterprise-scale pull request #914
Opened 2024-03-21 10:33 UTC by Slapper

## Overview/Summary

Add option to set `allow_non_virtual_wan_traffic` value to `true` or `false` in express route gateway.

## This PR fixes/adds/changes/removes

1. *Give the option to set `allow_non_virtual_wan_traffic` to true in azurerm_express_route_gateway resource*

### Breaking Changes

None 

## Testing Evidence

On the latest azurerm versions ( v3.48.0 and higher ) **azurerm_express_route_gateway** resource has the option to set this value to true. At the time of writing CAF module has no option available .

We saw this issue in our Dev environment during terraform plan :  the value was true so using a newer azurerm version the value goes to false, which is the default. 

```
  # module.vWAN.module.alz_connectivity.azurerm_express_route_gateway.virtual_wan["/subscriptions/xxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxx/resourceGroups/dev-connectivity/providers/Microsoft.Network/expressRouteGateways/dev-ergw-northeurope"] will be updated in-place
  ~ resource "azurerm_express_route_gateway" "virtual_wan" {
      ~ allow_non_virtual_wan_traffic = true -> false
        id                            = "/subscriptions/xxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxx/resourceGroups/dev-connectivity/providers/Microsoft.Network/expressRouteGateways/dev-ergw-northeurope"
        name                          = "dev-ergw-northeurope"
        tags                          = {
            "deployedBy"  = "terraform/azure/caf-enterprise-scale"
            "deployedFor" = "Dev"
        }
```

More info about this option can be found here :   https://github.com/hashicorp/terraform-provider-azurerm/pull/20667

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.

2024-03-21 11:43 UTC, Slapper commented
@microsoft-github-policy-service agree

2024-04-03 17:13 UTC, jaredfholgate commented
/azp run unit

2024-04-03 17:16 UTC, jaredfholgate requested changes
Need to run `terraform fmt -recursive` to fix the tests.

2024-04-03 17:16 UTC, jaredfholgate commented on resources.virtual_wan.tf
> +  allow_non_virtual_wan_traffic = each.value.template.allow_non_virtual_wan_traffic
Please run  `terraform fmt`. Thanks!

2024-04-04 09:33 UTC, Slapper commented
Hi @jaredfholgate ,

Feel free to move my branch to Azure project. 

Thanks!

2024-04-04 10:56 UTC, jaredfholgate commented
/azp run unit

2024-04-04 10:59 UTC, jaredfholgate commented
> Hi @jaredfholgate ,
> 
> Feel free to move my branch to Azure project.
> 
> ( i forgot to run the fmt with the recursive flag so maybe thats was the case ) Thanks!

That has fixed the linting issues, thanks. I will run and update the tests as nessecary now.

2024-04-05 07:18 UTC, jaredfholgate approved these changes
LGTM

2024-04-05 07:19 UTC, merged

2024-04-05 07:54 UTC, jaredfholgate commented
This was released in 5.2.0.

2024-04-05 10:45 UTC, birdnathan commented
@Slapper @jaredfholgate - something not quite right with that release
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/42775203/b419b3f7-fea1-4ed4-aa31-071f78e3f976)

2024-04-05 11:01 UTC, birdnathan commented
> @Slapper @jaredfholgate - something not quite right with that release ![image](https://private-user-images.githubusercontent.com/42775203/319966816-b419b3f7-fea1-4ed4-aa31-071f78e3f976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMTQ5NjcsIm5iZiI6MTcxMjMxNDY2NywicGF0aCI6Ii80Mjc3NTIwMy8zMTk5NjY4MTYtYjQxOWIzZjctZmVhMS00ZWQ0LWFhMzEtMDcxZjc4ZTNmOTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDEwNTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MjY5MGE3MmI0NTU1OWYzOTI2NWQ1NDBhYjVkMzA0OTQ5OThkZTA0NDFjNmI4ZWIxYjIwNjM1MGRlZDBiMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uW11fh8nQjs8G7ToIeeCyaDG1XSURBBl5YAANJMgXVQ)

Apologies, sorted. Nothing to do with your change. #907 introduced a breaking change. Had to tweak settings.connectivity to to also change threat_intelligence_allowlist = [] to threat_intelligence_allowlist = {}