Connectivity: Add OpenAI and Databricks Private Link DNS
Azure/terraform-azurerm-caf-enterprise-scale pull request #918
Opened 2024-03-28 07:29 UTC by nyanhp

## Overview/Summary

This PR fixes #890 by adding the OpenAI and Databricks Private Link DNS zones.

## This PR fixes/adds/changes/removes

1. #890

### Breaking Changes

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [ ] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

2024-05-08 13:40 UTC, glloyd2010f commented
Back seat quarterback here, but is there any objection to adding `scm.privatelink.azurewebsites.net` as well?

2024-05-31 07:25 UTC, tlfzhylj commented
Any chance for this to be completed?
This will also fix #851

2024-05-31 07:30 UTC, tlfzhylj approved these changes

2024-05-31 07:32 UTC, tlfzhylj requested changes
I did a search for another one of the private DNS zones, and it looks like they are referenced several places.

Example: https://github.com/search?q=repo%3AAzure%2Fterraform-azurerm-caf-enterprise-scale%20azure_database_for_postgresql_server&type=code

2024-06-06 17:25 UTC, matt-FFFFFF approved these changes

2024-06-06 17:25 UTC, merged